-- 013_seed_exercises.sql
-- Seeds the default exercise library (218 exercises) for a trainer.
-- Call this function once per trainer after their first program creation:
--   select seed_default_exercises('<trainer_profile_id>');

create or replace function seed_default_exercises(p_trainer_id uuid)
returns void as $$
begin
  insert into exercises (trainer_id, name, muscle_group, zone, movement_type, video_url)
  values
    (p_trainer_id, 'Press de banca plano con barra libre', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/GUgyKNEqGMY'),
    (p_trainer_id, 'Press de banca plano en máquina Smith', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/BqpVLoMH5v0'),
    (p_trainer_id, 'Press de banca plano con mancuernas', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/hlV6f0kHmeo'),
    (p_trainer_id, 'Press de banca plano en máquina articulada', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/HNaDJTSrI8s'),
    (p_trainer_id, 'Press de banca plano en máquina sentado', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/watch?v=z60iX0eYJG4'),
    (p_trainer_id, 'Press de banca plano en máquina articulada sentado', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/5UU5y2_aPyQ'),
    (p_trainer_id, 'Press inclinado con barra libre', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/XSiWdufUFQ8'),
    (p_trainer_id, 'Press inclinado en máquina Smith', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/r39cVRTjFU8'),
    (p_trainer_id, 'Press inclinado con mancuernas', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/ZaNyRjpoki8'),
    (p_trainer_id, 'Press inclinado en máquina articulada sentado', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/acC6hFJuQPU'),
    (p_trainer_id, 'Press inclinado en máquina sentado', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/sIw6FoF7WHE'),
    (p_trainer_id, 'Press inclinado en máquina articulada', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/656VwV0v3pE'),
    (p_trainer_id, 'Press declinado con barra libre', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/v79c-eDjBv8'),
    (p_trainer_id, 'Press declinado en máquina Smith', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/1GuZUji5KhI'),
    (p_trainer_id, 'Press declinado con mancuernas', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/JByJ3hwyRVE'),
    (p_trainer_id, 'Press declinado en máquina articulada sentado', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/iYPlm6rDDnY'),
    (p_trainer_id, 'Aperturas planas con mancuernas', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/NzefUogE_Bs'),
    (p_trainer_id, 'Aperturas en máquina', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/MENdoLpyj7c'),
    (p_trainer_id, 'Crossover en polea media', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/GhOC266dHqA'),
    (p_trainer_id, 'Aperturas inclinadas con mancuernas', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/ZeTzr8H_F8w'),
    (p_trainer_id, 'Crossover en polea baja', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/n8C9mCTziX0'),
    (p_trainer_id, 'Crossover', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/MoShufDdMWA'),
    (p_trainer_id, 'Aperturas inclinadas en polea', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/FteHJQw0KeU'),
    (p_trainer_id, 'Flexiones en el suelo', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/Umn1CcEoJIE'),
    (p_trainer_id, 'Pullover con mancuerna', 'Pecho', 'upper_body', 'push', 'https://www.youtube.com/shorts/vKCQHaG0Rj0'),
    (p_trainer_id, 'Jalón amplio con barra', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/_2MfZAj98tk'),
    (p_trainer_id, 'Jalón cerrado prono', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/vJTJjnP3TVU'),
    (p_trainer_id, 'Jalón cerrado supino', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/E-ftSvmzRME'),
    (p_trainer_id, 'Jalón cerrado con triángulo', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/ySLFHxmJ_Sc'),
    (p_trainer_id, 'Jalón en máquina articulada', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/2lSK2FIZWoA'),
    (p_trainer_id, 'Jalón en máquina', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/K8EmwD4nLGk'),
    (p_trainer_id, 'Jalón unilateral en polea alta', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/hR_D45hhNhA'),
    (p_trainer_id, 'Dominadas con agarre amplio', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/w1URM1Fv4gc'),
    (p_trainer_id, 'Dominadas con agarre cerrado', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/oPC_QP2SS0I'),
    (p_trainer_id, 'Gravitón con agarre amplio', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/lRCROSJkTKM'),
    (p_trainer_id, 'Gravitón con agarre cerrado', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/0XpicJ-jSqA'),
    (p_trainer_id, 'Remo en máquina con agarre neutro', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/e33bGJy4n28'),
    (p_trainer_id, 'Remo en máquina con agarre prono', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/SqvqaHqFvHA'),
    (p_trainer_id, 'Remo en máquina con agarre supino', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/4hM6WckLDDA'),
    (p_trainer_id, 'Remo en máquina articulada con agarre neutro', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/oeGnGldKrWs'),
    (p_trainer_id, 'Remo en máquina articulada con agarre prono', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/oE2jSe_HM18'),
    (p_trainer_id, 'Remo en máquina articulada con agarre supino', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/pE4dKxFepMA'),
    (p_trainer_id, 'Remo inclinado con agarre prono', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/e53vSzibkO0'),
    (p_trainer_id, 'Remo inclinado con agarre supino', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/w7j9nPqxTH4'),
    (p_trainer_id, 'Remo en barra T con agarre neutro', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/-cgEzc4defE'),
    (p_trainer_id, 'Remo en barra T con agarre prono', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/smc3Y-5coy8'),
    (p_trainer_id, 'Remo en barra T con agarre supino', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/CmjrHee2gGw'),
    (p_trainer_id, 'Remo serrucho', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/L2FuijYFTvE'),
    (p_trainer_id, 'Remo serrucho con agarre amplio', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/CNU-q6r9cEE'),
    (p_trainer_id, 'Remo bajo con agarre neutro', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/7lc8Ow4vIwA'),
    (p_trainer_id, 'Remo bajo con agarre prono', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/GcQI46Aay0A'),
    (p_trainer_id, 'Remo bajo con agarre supino', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/9JY2jPQbPmI'),
    (p_trainer_id, 'Remo inclinado en polea baja con agarre neutro', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/8Bsd6PySojo'),
    (p_trainer_id, 'Remo inclinado en polea baja con agarre prono', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/ITLdeeX1OEI'),
    (p_trainer_id, 'Remo inclinado en polea baja con agarre supino', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/M0ySpDSm9jo'),
    (p_trainer_id, 'Remo inclinado unilateral en polea baja', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/TGjm2GZ_i8s'),
    (p_trainer_id, 'Pull down con cuerda', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/bON_FlYHh8c'),
    (p_trainer_id, 'Pull down con barra', 'Espalda', 'upper_body', 'pull', 'https://www.youtube.com/shorts/1B1W0JWD-SM'),
    (p_trainer_id, 'Elevación lateral con mancuernas', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/ot9nwSC1JnA'),
    (p_trainer_id, 'Elevación lateral unilateral en polea', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/dgpts8LHOLc'),
    (p_trainer_id, 'Elevación lateral simultánea en polea', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/watch?v=DIbPha-D6Wg'),
    (p_trainer_id, 'Elevación lateral unilateral en banco inclinado', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/2a4yANFdNys'),
    (p_trainer_id, 'Elevación lateral unilateral con mancuerna', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/CG04WyDnud0'),
    (p_trainer_id, 'Elevación lateral en máquina', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/-vzaGAaUDjg'),
    (p_trainer_id, 'Elevación frontal con mancuerna con agarre neutro', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/IXbvmzQTSvU'),
    (p_trainer_id, 'Elevación frontal con mancuerna con agarre prono', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/GqZRmCow0rw'),
    (p_trainer_id, 'Elevación frontal con mancuerna con agarre supino', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/NRGYiMlBE-U'),
    (p_trainer_id, 'Elevación frontal con barra en polea con agarre prono', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/cCMl5hAgFvA'),
    (p_trainer_id, 'Elevación frontal con barra en polea con agarre supino', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/ayWm5IVfcX8'),
    (p_trainer_id, 'Elevación frontal con cuerda en polea', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/7jIaWstlQSI'),
    (p_trainer_id, 'Elevación frontal con barra con agarre prono', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/rBZKO52FyIM'),
    (p_trainer_id, 'Elevación frontal con barra con agarre supino', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/Pril-VoEPcI'),
    (p_trainer_id, 'Press militar con mancuernas', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/Gy6LpKErBT8'),
    (p_trainer_id, 'Press militar en máquina Smith', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/hejuwn4kffM'),
    (p_trainer_id, 'Press militar con barra', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/xHsnuP6r4fg'),
    (p_trainer_id, 'Press en máquina con agarre abierto', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/OfdNQFuFskU'),
    (p_trainer_id, 'Press en máquina con agarre cerrado', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/pcUIFz-2m2c'),
    (p_trainer_id, 'Press en máquina articulada con agarre abierto', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/5nsf4rO8grQ'),
    (p_trainer_id, 'Press en máquina articulada con agarre cerrado', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/2A_Klf2SBV8'),
    (p_trainer_id, 'Press Arnold', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/O3nHTDcdJDo'),
    (p_trainer_id, 'Pec deck inverso', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/Ck1zoqNh_io'),
    (p_trainer_id, 'Aperturas inversas con mancuernas', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/MHogGITTTBo'),
    (p_trainer_id, 'Aperturas inversas con mancuernas sentado', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/k7Dpu09tpmQ'),
    (p_trainer_id, 'Apertura inversa unilateral en polea', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/SfGmpuhTMM4'),
    (p_trainer_id, 'Apertura inversa simultánea en polea', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/VxGLc_ZL_04'),
    (p_trainer_id, 'Face pull', 'Hombros', 'upper_body', 'push', 'https://www.youtube.com/shorts/RSmMpmxiz6k'),
    (p_trainer_id, 'Curl de bíceps con mancuernas', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/MfsDC0ymFm8'),
    (p_trainer_id, 'Curl de bíceps con barra recta', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/dc330H9yN3Y'),
    (p_trainer_id, 'Curl de bíceps con barra Z', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/fjS0CqDR4v8'),
    (p_trainer_id, 'Curl de bíceps con barra en polea', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/x6JCKfdzPJE'),
    (p_trainer_id, 'Curl de bíceps con barra Z en polea', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/KM5khRAU74s'),
    (p_trainer_id, 'Curl de bíceps unilateral en polea', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/-DaCB9fc5yI'),
    (p_trainer_id, 'Curl alternado con mancuernas', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/xXp3mV3OOZo'),
    (p_trainer_id, 'Curl inclinado con mancuernas en banco inclinado', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/894iKk6bpaQ'),
    (p_trainer_id, 'Curl girado en banco inclinado con mancuernas', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/a1NPJFmCJ5o'),
    (p_trainer_id, 'Curl de bíceps en máquina', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/4DwBvjRwYwg'),
    (p_trainer_id, 'Curl concentrado', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/c0vYYI_mbXU'),
    (p_trainer_id, 'Curl con giro', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/ymOxKh5zgAQ'),
    (p_trainer_id, 'Curl martillo con mancuernas', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/hV4NpBjDHp8'),
    (p_trainer_id, 'Curl martillo con cuerda en polea', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/Z2u_WTbDlVc'),
    (p_trainer_id, 'Curl martillo unilateral en polea', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/D1nvczGoLtw'),
    (p_trainer_id, 'Curl martillo alternado con mancuernas', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/zjYiIf93ZBc'),
    (p_trainer_id, 'Curl martillo en banco inclinado', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/4LXelYv2Sfw'),
    (p_trainer_id, 'Curl tipo Scott con mancuernas', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/qkrVKiAadNk'),
    (p_trainer_id, 'Curl tipo Scott unilateral con mancuerna', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/qhRLio6bCRo'),
    (p_trainer_id, 'Curl tipo Scott en polea', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/t59dzwf4M0w'),
    (p_trainer_id, 'Curl tipo Scott con barra Z', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/zQuJCpJHbo0'),
    (p_trainer_id, 'Curl tipo Scott en máquina', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/90_d-DsrOkE'),
    (p_trainer_id, 'Curl inverso con barra Z', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/2izIqLamdiA'),
    (p_trainer_id, 'Curl inverso con barra en polea', 'Bíceps', 'upper_body', 'pull', 'https://www.youtube.com/shorts/uTbr841BLwU'),
    (p_trainer_id, 'Tríceps con barra recta en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/M88Bt4MMpkI'),
    (p_trainer_id, 'Tríceps con barra Z en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/-3s5GoUvIHE'),
    (p_trainer_id, 'Tríceps con cuerda en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/-QGC1cL6ETE'),
    (p_trainer_id, 'Tríceps unilateral en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/50fMcZBB0zY'),
    (p_trainer_id, 'Extensión de tríceps sobre la cabeza con barra Z en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/0-wbrF7xP9g'),
    (p_trainer_id, 'Extensión de tríceps sobre la cabeza con barra recta en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/VZ7H5PNqUIw'),
    (p_trainer_id, 'Extensión de tríceps sobre la cabeza con cuerda en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/etTuALjH3bo'),
    (p_trainer_id, 'Extensión de tríceps unilateral sobre la cabeza en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/Lji6KIAeMH0'),
    (p_trainer_id, 'Extensión de tríceps sobre banco en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/PfK51UcnHW0'),
    (p_trainer_id, 'Extensión de tríceps sobre la cabeza con barra Z', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/40Cx-IfJhA0'),
    (p_trainer_id, 'Extensión de tríceps sobre la cabeza con barra recta', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/Ifcvj9G_20w'),
    (p_trainer_id, 'Extensión de tríceps sobre la cabeza con mancuernas', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/Cd0-tP9utgM'),
    (p_trainer_id, 'Extensión de tríceps en máquina', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/j-hCzDEhriY'),
    (p_trainer_id, 'Extensión francesa de tríceps con barra Z en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/watch?v=iIiXIoWluSI'),
    (p_trainer_id, 'Extensión francesa de tríceps con barra recta en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/YtC8hg9iWBc'),
    (p_trainer_id, 'Extensión francesa de tríceps con cuerda en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/dMYGgTbtRIQ'),
    (p_trainer_id, 'Extensión francesa unilateral de tríceps en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/xNgLcxSfQtM'),
    (p_trainer_id, 'Extensión francesa con mancuerna sentado', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/_dtPoiFWZT4'),
    (p_trainer_id, 'Extensión francesa con mancuerna', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/XMkUtMtcOh0'),
    (p_trainer_id, 'Extensión francesa unilateral con mancuerna', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/EUcaGLnFaTU'),
    (p_trainer_id, 'Extensión francesa con barra Z', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/x1u6herdiO8'),
    (p_trainer_id, 'Patada de tríceps en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/0SMqbTQOq7Q'),
    (p_trainer_id, 'Patada de tríceps unilateral en polea', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/7Gdbq0aq3SA'),
    (p_trainer_id, 'Patada de tríceps con mancuernas', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/hg6jySXCaT0'),
    (p_trainer_id, 'Patada de tríceps unilateral con mancuerna', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/IkB040VfrVI'),
    (p_trainer_id, 'Fondos de tríceps en paralelas', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/x3sgFGDyTiQ'),
    (p_trainer_id, 'Fondos de tríceps en máquina', 'Tríceps', 'upper_body', 'push', 'https://www.youtube.com/shorts/YjyHrqCv9oM'),
    (p_trainer_id, 'Abdominal en máquina', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/HqqnFBqonR8'),
    (p_trainer_id, 'Abdominal superior', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/DV0Me9zSWGc'),
    (p_trainer_id, 'Abdominal superior en banco declinado', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/DeiNXNsEeWs'),
    (p_trainer_id, 'Abdominal superior con mancuerna', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/Ka1g9oaajKg'),
    (p_trainer_id, 'Abdominal en polea con cuerda', 'Abdomen', 'core', 'core', 'https://www.youtube.com/watch?v=6Tf4tw8-bgw'),
    (p_trainer_id, 'Abdominal tipo remo', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/L5LBreRCReg'),
    (p_trainer_id, 'Abdominal tijera', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/51Ryd2Ds2CI'),
    (p_trainer_id, 'Abdominal en bicicleta', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/OnQNhK0Ekgk'),
    (p_trainer_id, 'Abdominal inferior', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/In0EzoOAILw'),
    (p_trainer_id, 'Abdominal inferior en paralelas', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/vmqDIz3dVK4'),
    (p_trainer_id, 'Abdominal inferior en banco declinado', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/ayvoW6djYBg'),
    (p_trainer_id, 'Plancha', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/uxPlAbWFUDs'),
    (p_trainer_id, 'Plancha lateral', 'Abdomen', 'core', 'core', 'https://www.youtube.com/shorts/x2gzR9zzSCw'),
    (p_trainer_id, 'Sentadilla', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/3uZE_E11eg4'),
    (p_trainer_id, 'Sentadilla libre', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/nvVa-WFGwmM'),
    (p_trainer_id, 'Sentadilla con mancuernas', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/OwWCkwdATnE'),
    (p_trainer_id, 'Sentadilla tipo cáliz', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/MSmHm4f-qIc'),
    (p_trainer_id, 'Sentadilla en máquina Smith', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/1oipoiTpbJA'),
    (p_trainer_id, 'Prensa de piernas 45 grados', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/NY5fw4Zaofg'),
    (p_trainer_id, 'Prensa de piernas 180 grados', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/Y_u8jgMKiOI'),
    (p_trainer_id, 'Prensa de piernas 90 grados', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/qlT4S0wqlic'),
    (p_trainer_id, 'Prensa de piernas 45 grados unilateral', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/iKPoazkMI6Q'),
    (p_trainer_id, 'Prensa de piernas 180 grados unilateral', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/2GLF43030ig'),
    (p_trainer_id, 'Prensa de piernas 90 grados unilateral', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/ODL9Chp0eFM'),
    (p_trainer_id, 'Sentadilla Hack', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/ZsAu3REJnb0'),
    (p_trainer_id, 'Sentadilla Hack invertida', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/j4WcueuCAvU'),
    (p_trainer_id, 'Sentadilla Hack unilateral', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/9tYZ5FWhj68'),
    (p_trainer_id, 'Sentadilla Hack invertida unilateral', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/OEgn0BMWp-o'),
    (p_trainer_id, 'Extensión de piernas en máquina', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/PzIfB9MiiX8'),
    (p_trainer_id, 'Extensión de piernas unilateral en máquina', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/OjlRBt6itcc'),
    (p_trainer_id, 'Zancada con mancuernas', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/rltJymhFtHg'),
    (p_trainer_id, 'Zancada con barra', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/MYaDmJFxoeA'),
    (p_trainer_id, 'Zancada en máquina Smith', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/cGgGIklEJa4'),
    (p_trainer_id, 'Desplante', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/UORBklZn76k'),
    (p_trainer_id, 'Desplante con mancuernas', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/N2A6qU5dMBk'),
    (p_trainer_id, 'Desplante con barra', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/AFg7mj9mXy0'),
    (p_trainer_id, 'Curl nórdico inverso', 'Cuádriceps', 'lower_body', 'legs', 'https://www.youtube.com/shorts/uH_h1B5kDu0'),
    (p_trainer_id, 'Curl de piernas en máquina sentado', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/T46yKiz8laY'),
    (p_trainer_id, 'Curl de piernas unilateral en máquina sentado', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/KVOqkJLPh3U'),
    (p_trainer_id, 'Curl de piernas en máquina acostado', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/IXg1PQ_5gmw'),
    (p_trainer_id, 'Curl de piernas unilateral en máquina acostado', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/Uc_R_xX_j00'),
    (p_trainer_id, 'Curl de piernas de pie en máquina', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/L7jouj-t01E'),
    (p_trainer_id, 'Flexión de rodilla en polea', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/RkAg2O__4j4'),
    (p_trainer_id, 'Peso muerto rumano con mancuernas', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/KF3QpW6-jto'),
    (p_trainer_id, 'Peso muerto rumano con barra', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/raMtPJQ5f9A'),
    (p_trainer_id, 'Peso muerto rumano en polea', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/a3HbBbhJYA8'),
    (p_trainer_id, 'Peso muerto rumano en máquina Smith', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/DuBVWdchN4I'),
    (p_trainer_id, 'Peso muerto rumano unilateral con mancuerna', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/Vc4u9yelEiE'),
    (p_trainer_id, 'Buenos días con barra', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/KscJhVGv4uo'),
    (p_trainer_id, 'Buenos días en máquina Smith', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/jE6xoyboMfw'),
    (p_trainer_id, 'Curl nórdico', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/9HQ6_NFBu8U'),
    (p_trainer_id, 'Sentadilla búlgara', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/ZpIMkV6cf7c'),
    (p_trainer_id, 'Sentadilla búlgara con mancuernas', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/0KQOdTvfc5A'),
    (p_trainer_id, 'Sentadilla búlgara en máquina Smith', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/DcLFcm-_n9g'),
    (p_trainer_id, 'Zancada con step al frente con mancuerna', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/EJygSbSmtvw'),
    (p_trainer_id, 'Zancada con step al frente en máquina Smith', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/P94sxEZ4wlw'),
    (p_trainer_id, 'Peso muerto convencional', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/DjsLHZ4jxTU'),
    (p_trainer_id, 'Peso muerto sumo', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/m6IIorkQe8E'),
    (p_trainer_id, 'Sentadilla sumo con mancuerna', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/Jo1DFefVdrg'),
    (p_trainer_id, 'Sentadilla sumo con barra', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/DfsgqBqZ9vo'),
    (p_trainer_id, 'Sentadilla sumo en máquina Smith', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/lBWLeiZoNvU'),
    (p_trainer_id, 'Elevación pélvica con mancuerna', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/watch?v=dFpuY92JDLY'),
    (p_trainer_id, 'Elevación pélvica con barra', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/cOvGedlKlD4'),
    (p_trainer_id, 'Elevación pélvica en máquina Smith', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/watch?v=itUI9ZNBGYs'),
    (p_trainer_id, 'Elevación pélvica en máquina', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/EygaKO0sCLk'),
    (p_trainer_id, 'Elevación pélvica unilateral', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/prpbNaqWgE0'),
    (p_trainer_id, 'Extensión de cadera en máquina (glúteo)', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/pJ6NsHnC8LQ'),
    (p_trainer_id, 'Patada de glúteo', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/76BzXlotFho'),
    (p_trainer_id, 'Abducción de cadera en polea', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/oZODxYQcf1g'),
    (p_trainer_id, 'Máquina de abducción de cadera', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/nabhYLtz8Gg'),
    (p_trainer_id, 'Máquina de abducción de cadera inclinada', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/CblCvLRAPB8'),
    (p_trainer_id, 'Máquina de abducción de cadera de pie', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/cXQqgSphtwo'),
    (p_trainer_id, 'Máquina de aducción de cadera (aductores)', 'Isquiotibiales y Glúteos', 'lower_body', 'legs', 'https://www.youtube.com/shorts/K0PtIEb-O_w'),
    (p_trainer_id, 'Elevación de talones de pie', 'Pantorrillas', 'lower_body', 'legs', 'https://www.youtube.com/shorts/KCoe6a_cAkM'),
    (p_trainer_id, 'Elevación de talones de pie unilateral', 'Pantorrillas', 'lower_body', 'legs', 'https://www.youtube.com/shorts/GVOZWTDE6Ro'),
    (p_trainer_id, 'Elevación de talones con mancuerna unilateral', 'Pantorrillas', 'lower_body', 'legs', 'https://www.youtube.com/shorts/GVOZWTDE6Ro'),
    (p_trainer_id, 'Elevación de talones de pie en máquina Smith', 'Pantorrillas', 'lower_body', 'legs', 'https://www.youtube.com/shorts/cETqVlftyJs'),
    (p_trainer_id, 'Elevación de talones en prensa de piernas 45 grados', 'Pantorrillas', 'lower_body', 'legs', 'https://www.youtube.com/shorts/tWdOuSEM3NM'),
    (p_trainer_id, 'Elevación de talones en prensa de piernas 180 grados', 'Pantorrillas', 'lower_body', 'legs', 'https://www.youtube.com/shorts/PkXChiAQDh8'),
    (p_trainer_id, 'Elevación de talones en máquina', 'Pantorrillas', 'lower_body', 'legs', 'https://www.youtube.com/shorts/BQdX4UN3XW0'),
    (p_trainer_id, 'Elevación de talones sentado en máquina', 'Pantorrillas', 'lower_body', 'legs', 'https://www.youtube.com/shorts/ulHIn4HtjCs');
end;
$$ language plpgsql;
